import frappe
import os


def after_install():
    create_custom_fields()
    create_property_setters()
    create_role_permissions()
    backfill_moderator_role()
    sync_lms_template()


def after_migrate():
    create_custom_fields()
    create_property_setters()
    create_role_permissions()
    backfill_moderator_role()
    sync_lms_template()


def sync_lms_template():
    """
    Generates _lms.html and _lms.py in lms_plus/www/ from the installed LMS version.
    Runs on every bench migrate — stays in sync with any LMS version.
    Without these files, Frappe falls back to LMS originals cleanly.
    """
    try:
        lms_html_src = frappe.get_app_path("lms", "www", "_lms.html")
        our_www = frappe.get_app_path("lms_plus", "www")

        if not os.path.exists(lms_html_src):
            frappe.logger().warning("LMS Plus: lms/_lms.html not found — skipping sync")
            return

        os.makedirs(our_www, exist_ok=True)

        # 1. Generate _lms.html — copy from LMS and inject our script tag
        with open(lms_html_src, "r") as f:
            html = f.read()

        script_tag = '    <script src="/assets/lms_plus/js/lms_plus.js"></script>\n'
        if "lms_plus.js" not in html:
            html = html.replace("</body>", script_tag + "</body>")

        with open(os.path.join(our_www, "_lms.html"), "w") as f:
            f.write(html)

        # 2. Generate _lms.py — extends LMS context with role data
        lms_py = '''# Auto-generated by lms_plus setup.py — do not edit manually
# Re-generated on every bench migrate via sync_lms_template()

no_cache = 1


def get_context():
    import frappe
    try:
        from lms.www._lms import get_context as lms_get_context
        context = lms_get_context()
    except Exception:
        context = frappe._dict()
        try:
            from lms.www._lms import get_boot
            context.boot = get_boot()
        except Exception:
            context.boot = frappe._dict({
                "frappe_version": frappe.__version__,
                "read_only_mode": frappe.flags.read_only,
                "csrf_token": frappe.sessions.get_csrf_token(),
                "site_name": frappe.local.site,
                "lms_path": "lms",
            })
    try:
        user = frappe.session.user
        roles = frappe.get_roles(user)
        context.boot["user"] = user
        context.boot["user_roles"] = roles
        context.boot["is_lms_manager"] = (
            "LMS Manager" in roles
            or "Administrator" in roles
            or "System Manager" in roles
        )
    except Exception:
        pass
    return context
'''
        with open(os.path.join(our_www, "_lms.py"), "w") as f:
            f.write(lms_py)

        frappe.logger().info("LMS Plus: _lms.html and _lms.py synced from LMS successfully")

    except Exception:
        frappe.log_error(
            title="LMS Plus: template sync failed",
            message=frappe.get_traceback(),
        )


def create_custom_fields():
    fields = [
        {
            "dt": "LMS Batch",
            "label": "Department",
            "fieldname": "custom_department",
            "fieldtype": "Link",
            "options": "Department",
            "insert_after": "end_date",
        },
        {
            "dt": "LMS Batch",
            "label": "Manager",
            "fieldname": "custom_manager",
            "fieldtype": "Link",
            "options": "User",
            "insert_after": "custom_department",
        },
        {
            "dt": "LMS Course Progress",
            "label": "Video Position (seconds)",
            "fieldname": "custom_video_position",
            "fieldtype": "Float",
            "insert_after": "lesson",
        },
        {
            "dt": "LMS Course",
            "label": "Prerequisite Course",
            "fieldname": "custom_prerequisite_course",
            "fieldtype": "Link",
            "options": "LMS Course",
            "insert_after": "disable_self_learning",
        },
    ]
    for field in fields:
        if frappe.db.exists("Custom Field", f"{field['dt']}-{field['fieldname']}"):
            continue
        frappe.get_doc({"doctype": "Custom Field", **field}).insert(ignore_permissions=True)
    frappe.db.commit()


def create_property_setters():
    fields_to_fix = [
        "start_date", "end_date", "start_time", "end_time",
        "timezone", "description", "instructors", "batch_details",
    ]
    for fieldname in fields_to_fix:
        ps_name = f"LMS Batch-{fieldname}-reqd"
        if frappe.db.exists("Property Setter", ps_name):
            continue
        frappe.get_doc({
            "doctype": "Property Setter",
            "name": ps_name,
            "doctype_or_field": "DocField",
            "doc_type": "LMS Batch",
            "field_name": fieldname,
            "property": "reqd",
            "value": "0",
            "property_type": "Check",
        }).insert(ignore_permissions=True)
    frappe.db.commit()


def create_role_permissions():
    """
    Grants LMS Manager the same full CRUD rights that Moderator already has
    across the entire LMS content/operations domain. LMS Manager is an
    lms_plus role and was never wired into the core LMS DocPerms, so course,
    batch, certificate, quiz etc. editing silently failed permission checks
    for LMS Managers even though the lms_plus UI shows those controls.

    This list mirrors every non-child-table doctype where Moderator (LMS's
    own broadest built-in role) has full read/write/create rights — i.e.
    LMS Manager becomes "admin, scoped to the LMS domain" rather than a
    site-wide Administrator equivalent.
    """
    from frappe.permissions import add_permission, update_permission_property

    doctypes = [
        "Course Chapter", "Course Evaluator", "Course Lesson",
        "LMS Assignment", "LMS Assignment Submission",
        "LMS Badge", "LMS Badge Assignment",
        "LMS Batch", "LMS Batch Enrollment", "LMS Batch Feedback",
        "LMS Category", "LMS Certificate", "LMS Certificate Evaluation",
        "LMS Certificate Request", "LMS Coupon", "LMS Course",
        "LMS Course Progress", "LMS Course Review", "LMS Enrollment",
        "LMS Google Meet Settings", "LMS Lesson Note",
        "LMS Live Class", "LMS Live Class Participant", "LMS Payment",
        "LMS Program", "LMS Programming Exercise",
        "LMS Programming Exercise Submission", "LMS Question", "LMS Quiz",
        "LMS Settings", "LMS Source", "LMS Timetable Template",
        "LMS Video Watch Duration", "LMS Zoom Settings",
    ]
    rights = [
        "read", "write", "create", "delete",
        "email", "export", "import", "print", "report", "share",
    ]

    for doctype in doctypes:
        if not frappe.db.exists("DocType", doctype):
            continue
        if not frappe.db.exists("Custom DocPerm", {"parent": doctype, "role": "LMS Manager"}):
            add_permission(doctype, "LMS Manager", 0)
        for right in rights:
            update_permission_property(doctype, "LMS Manager", 0, right, 1)

    frappe.clear_cache()
    frappe.db.commit()


def backfill_moderator_role():
    """
    One-time (idempotent) catch-up for users who already had LMS Manager
    assigned before api.user.sync_moderator_role existed. See that
    function's docstring for why LMS Manager needs to carry Moderator too.
    """
    users = frappe.get_all(
        "Has Role", filters={"role": "LMS Manager", "parenttype": "User"}, pluck="parent"
    )
    for user in users:
        if frappe.db.exists("Has Role", {"parent": user, "parenttype": "User", "role": "Moderator"}):
            continue
        frappe.get_doc({
            "doctype": "Has Role",
            "parent": user,
            "parenttype": "User",
            "parentfield": "roles",
            "role": "Moderator",
        }).insert(ignore_permissions=True)

    frappe.clear_cache()
    frappe.db.commit()
